### PR TITLE
[my-example-branch] Added feature

### PR DESCRIPTION
**Pull request by amenasria**
Approve it!!!

### CODE REVIEW

**Review by CelianR — COMMENTED** [review]
...

**Review by KevinFairise2 — CHANGES_REQUESTED** [review]
I've been asked to do so

**Review by CelianR — COMMENTED** [review]
....

**Review by CelianR — APPROVED** [review]

**Review by CelianR — CHANGES_REQUESTED** [review]
Please don't merge!

**Review by CelianR — CHANGES_REQUESTED** [review]
...

**Review by CelianR — CHANGES_REQUESTED** [review]
ahhhh!

**Review by CelianR — APPROVED** [review]

**Pull request closed without merging**
